[package]
name = "popcat"
version = "0.1.0"
authors = ["saltyaom <saltyaom@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.8"
headless_chrome = "0.9.0"
